"""Add precision column to CurrencyRate

Revision ID: 4e540a693347
Revises: 
Create Date: 2024-11-02 08:07:50.347598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e540a693347'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precision', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency_rate', schema=None) as batch_op:
        batch_op.drop_column('precision')

    # ### end Alembic commands ###
