"""Set currency_code & created_at are union uniqeu index

Revision ID: 8a7f95b2765b
Revises: 4e540a693347
Create Date: 2024-11-02 08:43:05.615276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7f95b2765b'
down_revision = '4e540a693347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency_rate', schema=None) as batch_op:
        batch_op.drop_index('currency_code')
        batch_op.create_unique_constraint('uix_currency_created_at', ['currency_code', 'created_at'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency_rate', schema=None) as batch_op:
        batch_op.drop_constraint('uix_currency_created_at', type_='unique')
        batch_op.create_index('currency_code', ['currency_code'], unique=True)

    # ### end Alembic commands ###
